before_script:
  - export REGISTRY_USER=schmunk42
  - export REGISTRY_EMAIL=reg@h17n.de
  - export REGISTRY_HOST=https://index.docker.io/v1/
  - export CI_APP_VOLUME=$CI_PROJECT_DIR

build-php5:
  stage: build
  script:
    - cd phundament/php-one/5.6-7.0
    - docker build --pull -t phundament/php-one:5.6-fpm -f Dockerfile-5.6-fpm .

build-php5-apache:
  stage: build
  script:
    - cd phundament/php-one/5.6-7.0
    - docker build --pull -t phundament/php-one:5.6-apache -f Dockerfile-5.6-apache .

build-php7:
  stage: build
  script:
    - cd phundament/php-one/5.6-7.0
    - docker build --pull -t phundament/php-one:7.0-fpm -f Dockerfile-7.0-fpm .

build-nginx:
  stage: build
  script:
    - cd phundament/nginx-one/1.9
    - docker build --pull -t phundament/nginx-one:1.9 -f Dockerfile .

test:
  stage: test
  script:
    - docker run --rm -v $CI_APP_VOLUME/tests:/tests phundament/php-one:5.6-fpm php -e /tests/test_functions.php

test-dev:
  stage: test
  allow_failure: true
  script:
    - docker run --rm -v $CI_APP_VOLUME/tests:/tests phundament/php-one:5.6-apache php -e /tests/test_functions.php
    - docker run --rm -v $CI_APP_VOLUME/tests:/tests phundament/php-one:7.0-fpm php -e /tests/test_functions.php


deploy:
  stage: deploy
  script:
    - sh build/deploy.sh
  except:
    - develop



build-legacy:
  script:
     - sed -i "s|0000000000000000000000000000000000000000|${GITHUB_TOKEN}|" phundament/php/cli-dev/config.json
     - touch -acmt 1010101011 phundament/php/cli-dev/config.json
     - make -f Makefile-schmunk42 build
  stage: build
rspec-legacy:
  script:
     - sh tests-4.0/run.sh
  stage: test
deploy-legacy:
  script:
    - sh tests-4.0/release.sh
  except:
    - develop
  stage: deploy
