before_script:
  - export REGISTRY_USER=schmunk42
  - export REGISTRY_EMAIL=reg@h17n.de
  - export REGISTRY_HOST=https://index.docker.io/v1/
  - export CI_APP_VOLUME=$CI_PROJECT_DIR
  - sed -i "s|0000000000000000000000000000000000000000|${GITHUB_TOKEN}|" phundament/php-one/5.6-7.0/container-files/config.json
  - touch -acmt 1010101011 phundament/php-one/5.6-7.0/container-files/config.json


build-php5:
  stage: build
  script:
    - cd phundament/php-one/5.6-7.0
    - docker build --pull -t phundament/php-one:5.6-fpm -f Dockerfile-5.6-fpm .

build-php5-apache:
  stage: build
  script:
    - cd phundament/php-one/5.6-7.0
    - docker build --pull -t phundament/php-one:5.6-apache -f Dockerfile-5.6-apache .

build-php7:
  stage: build
  script:
    - cd phundament/php-one/5.6-7.0
    - docker build --pull -t phundament/php-one:7.0-fpm -f Dockerfile-7.0-fpm .

build-nginx:
  stage: build
  script:
    - cd phundament/nginx-one/1.9
    - docker build --pull -t phundament/nginx-one:1.9 -f Dockerfile .

test-images:
  stage: test
  script:
    - docker run --rm -v $CI_APP_VOLUME/tests:/tests phundament/php-one:5.6-fpm php -e /tests/phundament/php-one/test_functions.php

test-images-allow-fail:
  stage: test
  allow_failure: true
  script:
    - set -e
    - EXIT_CODE=0
    - docker run --rm -v $CI_APP_VOLUME/tests:/tests phundament/php-one:5.6-fpm php -v || EXIT_CODE=1
    - docker run --rm -v $CI_APP_VOLUME/tests:/tests phundament/php-one:5.6-apache php -v || EXIT_CODE=1
    - docker run --rm -v $CI_APP_VOLUME/tests:/tests phundament/php-one:7.0-fpm php -v || EXIT_CODE=1
    - docker run --rm -v $CI_APP_VOLUME/tests:/tests phundament/php-one:5.6-fpm composer diagnose || EXIT_CODE=1
    - docker run --rm -v $CI_APP_VOLUME/tests:/tests phundament/php-one:5.6-fpm climb || EXIT_CODE=1
    - docker run --rm -v $CI_APP_VOLUME/tests:/tests phundament/php-one:5.6-apache php -e /tests/phundament/php-one/test_functions.php || EXIT_CODE=1
    - docker run --rm -v $CI_APP_VOLUME/tests:/tests phundament/php-one:7.0-fpm php -e /tests/phundament/php-one/test_functions.php || EXIT_CODE=1
    - exit $EXIT_CODE

lint-dockerfiles:
  stage: test
  allow_failure: true
  script:
    - export DOCKERFILE_PATH=phundament/php-one/5.6-7.0
    - export DOCKERFILE=Dockerfile-5.6-fpm
	- docker run --rm -v "$(PWD)/$(DOCKERFILE_PATH)/$(DOCKERFILE)":/Dockerfile:ro redcoolbeans/dockerlint
	- docker run --rm --privileged -v $(PWD)/$(DOCKERFILE_PATH):/root/ projectatomic/dockerfile-lint dockerfile_lint -f $(DOCKERFILE)

deploy:
  stage: deploy
  script:
    - sh build/deploy.sh
  except:
    - develop